management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

logging:
  level:
    com.netflix: INFO
    org.springframework: INFO
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
