management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api
  ignoredServices: "*"
  routes:
    licensestatic:
      path: /licensestatic/**
      serviceId: licensestatic
    organizationservice: /organization/**
    licensingservice: /licensing/**

ribbon:
  eureka:
    enabled: false

licensestatic:
  ribbon:
    listOfServers: http://licensingservice1:8080,http://licensingservice2:8081
