management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

zuul:
  SimpleHostRoutingFilter:
    route:
      disable: true

logging:
  level:
    com.netflix: DEBUG
    org.springframework: DEBUG
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
