logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          contentType: application/json
      kafka:
        binder:
          brokers: localhost
  zipkin:
    baseUrl: localhost:9411

