eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eurekaserver:8761/eureka

  server:
    error:
      include-exception: true
