logging:
  level:
    com.netflix: WARN
    org.springframework: WARN
    com.thoughtmechanix: DEBUG

server:
  prot: 5555

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  zipkin:
    baseUrl: localhost:9411
