eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

logback:
  access:
    enabled: true

#server:
#  error:
#    include-exception: true

