logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    waitTimeInMsWhenSyncEmpty: 0

