server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/jso/dev/work_java/workspace-microservice/coding-workshop/chapter03/confsvr/src/main/resources/config/licensingservice
